#!/usr/bin/perl
#
# Uses PurpleWiki::Rss to create a full RSS 1.0 feed of the
# last 15 changes on the wiki. Can be run from cron or as
# needed.

use PurpleWiki::Config;
use PurpleWiki::Rss;

my $config = new PurpleWiki::Config('/home/cdent/testpurple');
my $rss = new PurpleWiki::Rss(config => $config);
print $rss->getRSS();
